input_number:
  bag_in_tank:
    name: Bag in tank
    max: 3
    min: 0
    step: 1
  reservoir_pellet:
    name: Quantité de pellets dans le reservoir
    max: 45
    min: 0
    unit_of_measurement: "Kg"
    step: 1

  pellets_before_service_before_bag_add:
    name: Valleur pellets avant entretien avant ajout sac
    max: 2000
    min: -700
    unit_of_measurement: "Kg"
    step: 1

  reservoir_pellet_after_bag_add:
    name: Quantité de pellets dans le reservoir au dernier remplissage
    max: 45
    min: 0
    unit_of_measurement: "Kg"
    step: 1

sensor:
  - platform: rest
    resource: !secret gsg_json
    name: Sacs restants
    value_template: "{{ value_json.NbrSacRestant }}"
    scan_interval: 3600

  - platform: template
    sensors:
      reservoir_pellet:
        friendly_name: "Quantité de pellets dans le reservoir"
        value_template: >-
          {% if is_state('sensor.rika_domo_pellets_before_service', 'unknow')%}
            {{int(states('sensor.reservoir_pellet'),0)}}
          {% elif is_state('sensor.rika_domo_pellets_before_service', 'unavailable')%}
            {{int(states('sensor.reservoir_pellet'),0)}}
          {% elif int(states('input_number.reservoir_pellet_after_bag_add'),0) - (int(states('input_number.pellets_before_service_before_bag_add'),0) - int(states('sensor.rika_domo_pellets_before_service'),0) ) > 45 %}
            {{45}}
          {% elif int(states('input_number.reservoir_pellet_after_bag_add'),0) - (int(states('input_number.pellets_before_service_before_bag_add'),0) - int(states('sensor.rika_domo_pellets_before_service'),0) ) < 1 %}
            {{0}}
          {% else %}
            {{int(states('input_number.reservoir_pellet_after_bag_add'),0) - (int(states('input_number.pellets_before_service_before_bag_add'),0) - int(states('sensor.rika_domo_pellets_before_service'),0) )}}
          {% endif %}
        unit_of_measurement: "Kg"


switch:
  - platform: command_line
    switches:
      rajout_1_sac:
        command_on: !secret gsg_1_sac_command

